import { Anime } from "@/types";

// Using a reliable placeholder service that doesn't redirect
const img = (seed: number, w = 600, h = 800) =>
  `https://picsum.photos/${w}/${h}?random=${seed}`;

export const animes: Anime[] = [
  {
    id: "attack-on-titan",
    name: "Bakugan, Battle Planet",
    genre: ["Acción", "Drama", "Fantasía"],
    coverImage: img(10, 800, 450),
    accentColor: "#00c2ff",
    description:
      "La humanidad lucha por su supervivencia contra titanes devoradores. Una era de guerra y sacrificio.",
    figuras: [
      {
        id: "eren-yeager",
        animeId: "attack-on-titan",
        name: "Eren Yeager — Forma Titan",
        price: 4500,
        condition: "Excelente",
        scale: "1/8",
        material: "PVC + ABS",
        height: "28 cm",
        description: "Figura premium de Eren en su forma titan del ataque final. Detalles pintados a mano con acabado mate premium.",
        images: [img(11), img(12), img(13), img(14)],
        inStock: true,
      },
      {
        id: "levi-ackerman",
        animeId: "attack-on-titan",
        name: "Levi Ackerman — ODM Gear",
        price: 5200,
        condition: "Muy Bueno",
        scale: "1/7",
        material: "PVC + ABS",
        height: "24 cm",
        description: "El Capitán Levi en plena acción con equipo ODM desplegado. Base dinámica incluida.",
        images: [img(15), img(16), img(17), img(18)],
        inStock: true,
      },
      {
        id: "mikasa-ackerman",
        animeId: "attack-on-titan",
        name: "Mikasa Ackerman — Shiganshina",
        price: 3800,
        condition: "Bueno",
        scale: "1/8",
        material: "PVC",
        height: "22 cm",
        description: "Mikasa con el uniforme del Cuerpo de Reconocimiento, expresión seria y determinada.",
        images: [img(19), img(20), img(21), img(22)],
        inStock: false,
      },
    ],
  },
  {
    id: "demon-slayer",
    name: "Tokyo Ghoul",
    genre: ["Acción", "Sobrenatural", "Histórico"],
    coverImage: img(30, 800, 450),
    accentColor: "#ff4d6d",
    description: "Tanjiro Kamado emprende una misión para salvar a su hermana y vengar a su familia.",
    figuras: [
      {
        id: "tanjiro-water",
        animeId: "demon-slayer",
        name: "Tanjiro Kamado — Water Breathing",
        price: 4200,
        condition: "Excelente",
        scale: "1/8",
        material: "PVC + ABS",
        height: "26 cm",
        description: "Tanjiro con la espada en posición de Respiración del Agua, efecto de agua transparente incluido.",
        images: [img(31), img(32), img(33), img(34)],
        inStock: true,
      },
      {
        id: "zenitsu-thunder",
        animeId: "demon-slayer",
        name: "Zenitsu Agatsuma — Thunder Clap",
        price: 3900,
        condition: "Muy Bueno",
        scale: "1/8",
        material: "PVC + ABS",
        height: "22 cm",
        description: "Zenitsu en la primera forma del Rayo, base con efecto de descarga eléctrica.",
        images: [img(35), img(36), img(37), img(38)],
        inStock: true,
      },
      {
        id: "nezuko-blood-demon",
        animeId: "demon-slayer",
        name: "Nezuko Kamado — Blood Demon Art",
        price: 4800,
        condition: "Excelente",
        scale: "1/7",
        material: "PVC + ABS",
        height: "20 cm",
        description: "Nezuko en modo demonio con llamas rosadas de su arte demoníaco, edición limitada.",
        images: [img(39), img(40), img(41), img(42)],
        inStock: true,
      },
    ],
  },
  {
    id: "jujutsu-kaisen",
    name: "Death Note",
    genre: ["Acción", "Sobrenatural", "Horror"],
    coverImage: img(50, 800, 450),
    accentColor: "#a855f7",
    description: "Yuji Itadori se convierte en recipiente del demonio maldito más poderoso de todos los tiempos.",
    figuras: [
      {
        id: "gojo-satoru",
        animeId: "jujutsu-kaisen",
        name: "Gojo Satoru — Infinity Domain",
        price: 6500,
        condition: "Excelente",
        scale: "1/7",
        material: "PVC + ABS",
        height: "30 cm",
        description: "Gojo con ojos azules brillantes y aura de infinito. La figura más detallada de la colección.",
        images: [img(51), img(52), img(53), img(54)],
        inStock: true,
      },
      {
        id: "yuji-divergent-fist",
        animeId: "jujutsu-kaisen",
        name: "Yuji Itadori — Divergent Fist",
        price: 3700,
        condition: "Muy Bueno",
        scale: "1/8",
        material: "PVC",
        height: "24 cm",
        description: "Yuji en pose de combate con energía maldita rodeando sus puños.",
        images: [img(55), img(56), img(57), img(58)],
        inStock: true,
      },
      {
        id: "ryomen-sukuna",
        animeId: "jujutsu-kaisen",
        name: "Ryomen Sukuna — King of Curses",
        price: 5500,
        condition: "Excelente",
        scale: "1/7",
        material: "PVC + ABS",
        height: "27 cm",
        description: "El Rey de las Maldiciones con sus cuatro brazos y tatuajes detallados, aura maligna incluida.",
        images: [img(59), img(60), img(61), img(62)],
        inStock: false,
      },
    ],
  },
  {
    id: "one-piece",
    name: "Boku No Hero",
    genre: ["Aventura", "Fantasía", "Comedia"],
    coverImage: img(70, 800, 450),
    accentColor: "#f97316",
    description: "Monkey D. Luffy navega los Grand Line en busca del legendario tesoro Boku No Hero.",
    figuras: [
      {
        id: "luffy-gear5",
        animeId: "one-piece",
        name: "Monkey D. Luffy — Gear 5th",
        price: 5800,
        condition: "Excelente",
        scale: "1/7",
        material: "PVC + ABS",
        height: "28 cm",
        description: "Luffy en Gear 5 con el poder del Sun God Nika, cabello y ropa blancos, risa icónica.",
        images: [img(71), img(72), img(73), img(74)],
        inStock: true,
      },
      {
        id: "zoro-three-swords",
        animeId: "one-piece",
        name: "Roronoa Zoro — Santoryu",
        price: 4600,
        condition: "Muy Bueno",
        scale: "1/8",
        material: "PVC + ABS",
        height: "26 cm",
        description: "Zoro con las tres espadas en posición Oni Giri, cicatriz en el ojo perfectamente detallada.",
        images: [img(75), img(76), img(77), img(78)],
        inStock: true,
      },
      {
        id: "nami-climatact",
        animeId: "one-piece",
        name: "Nami — Clima-Tact Thunderbolt",
        price: 3500,
        condition: "Bueno",
        scale: "1/8",
        material: "PVC",
        height: "21 cm",
        description: "Nami con su bastón Clima-Tact y efecto de rayo, vestimenta del arco Enies Lobby.",
        images: [img(79), img(80), img(81), img(82)],
        inStock: true,
      },
    ],
  },
  {
    id: "naruto",
    name: "Naruto",
    genre: ["Acción", "Aventura", "Artes Marciales"],
    coverImage: img(90, 800, 450),
    accentColor: "#fbbf24",
    description: "Un joven ninja con el espíritu del zorro de nueve colas busca convertirse en Hokage.",
    figuras: [
      {
        id: "naruto-kurama",
        animeId: "naruto",
        name: "Naruto Uzumaki — Kurama Mode",
        price: 5100,
        condition: "Excelente",
        scale: "1/8",
        material: "PVC + ABS",
        height: "25 cm",
        description: "Naruto en modo Kurama completo con aura de chakra naranja y runas del sello.",
        images: [img(91), img(92), img(93), img(94)],
        inStock: true,
      },
      {
        id: "sasuke-rinnegan",
        animeId: "naruto",
        name: "Sasuke Uchiha — Rinne Sharingan",
        price: 4900,
        condition: "Muy Bueno",
        scale: "1/8",
        material: "PVC + ABS",
        height: "24 cm",
        description: "Sasuke adulto con Rinne Sharingan activado y Susano'o parcial en la base.",
        images: [img(95), img(96), img(97), img(98)],
        inStock: true,
      },
      {
        id: "itachi-anbu",
        animeId: "naruto",
        name: "Itachi Uchiha — ANBU Black Ops",
        price: 4300,
        condition: "Excelente",
        scale: "1/8",
        material: "PVC + ABS",
        height: "23 cm",
        description: "Itachi con la máscara ANBU en mano y cuervos negros detallados alrededor.",
        images: [img(99), img(100), img(101), img(102)],
        inStock: false,
      },
    ],
  },
  {
    id: "chainsaw-man",
    name: "Dragon Ball",
    genre: ["Acción", "Horror", "Sobrenatural"],
    coverImage: img(110, 800, 450),
    accentColor: "#ef4444",
    description: "Denji fusiona su cuerpo con Pochita y se convierte en el Dragon Ball, cazador de demonios.",
    figuras: [
      {
        id: "denji-chainsaw",
        animeId: "chainsaw-man",
        name: "Denji — Chainsaw Devil",
        price: 5400,
        condition: "Excelente",
        scale: "1/7",
        material: "PVC + ABS",
        height: "29 cm",
        description: "Denji transformado con las motosierras del pecho y cabeza, salpicaduras de sangre en base.",
        images: [img(111), img(112), img(113), img(114)],
        inStock: true,
      },
      {
        id: "makima-control",
        animeId: "chainsaw-man",
        name: "Makima — Control Devil",
        price: 4700,
        condition: "Muy Bueno",
        scale: "1/8",
        material: "PVC + ABS",
        height: "23 cm",
        description: "Makima con sus ojos de anillos concéntricos brillantes y aura manipuladora.",
        images: [img(115), img(116), img(117), img(118)],
        inStock: true,
      },
      {
        id: "power-blood",
        animeId: "chainsaw-man",
        name: "Power — Blood Devil",
        price: 4100,
        condition: "Bueno",
        scale: "1/8",
        material: "PVC",
        height: "22 cm",
        description: "Power con cuernos de sangre solidificada y su martillo Blood Hammer, expresión desafiante.",
        images: [img(119), img(120), img(121), img(122)],
        inStock: true,
      },
    ],
  },
  {
    id: "spy-x-family",
    name: "Spy x Family",
    genre: ["Comedia", "Acción", "Espionaje"],
    coverImage: img(130, 800, 450),
    accentColor: "#34d399",
    description: "Un espía, una asesina y una telepática forman la familia perfectamente falsa.",
    figuras: [
      {
        id: "loid-forger",
        animeId: "spy-x-family",
        name: "Loid Forger — Twilight",
        price: 4000,
        condition: "Excelente",
        scale: "1/8",
        material: "PVC + ABS",
        height: "24 cm",
        description: "Loid en traje de agente con gadgets de espionaje, pose de acción elegante.",
        images: [img(131), img(132), img(133), img(134)],
        inStock: true,
      },
      {
        id: "yor-forger",
        animeId: "spy-x-family",
        name: "Yor Forger — Thorn Princess",
        price: 4400,
        condition: "Muy Bueno",
        scale: "1/8",
        material: "PVC + ABS",
        height: "23 cm",
        description: "Yor con su corona de espinas y agujas de combate, vestido rojo de asesina.",
        images: [img(135), img(136), img(137), img(138)],
        inStock: true,
      },
      {
        id: "anya-forger",
        animeId: "spy-x-family",
        name: "Anya Forger — Heh Face",
        price: 3200,
        condition: "Excelente",
        scale: "1/8",
        material: "PVC",
        height: "16 cm",
        description: "Anya con su expresión icónica 'heh', uniforme de Eden Academy, chibi adorable.",
        images: [img(139), img(140), img(141), img(142)],
        inStock: true,
      },
    ],
  },
];

export const getAnimeById = (id: string): Anime | undefined =>
  animes.find((a) => a.id === id);

export const getFiguraById = (
  animeId: string,
  figuraId: string
): { anime: Anime; figura: Anime["figuras"][0] } | undefined => {
  const anime = getAnimeById(animeId);
  if (!anime) return undefined;
  const figura = anime.figuras.find((f) => f.id === figuraId);
  if (!figura) return undefined;
  return { anime, figura };
};